"""Add activation_code to User model

Revision ID: 26e35fce7adf
Revises: 7ca80d2d5e83
Create Date: 2025-03-21 17:03:28.181130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e35fce7adf'
down_revision: Union[str, None] = '7ca80d2d5e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('activation_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_code')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
